---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: cletus
    name: postgres-pod

spec:
  containers:
    - name: postgres-app
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: cletus
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
      ports:
        - containerPort: 5432
...
