---
apiVersion: v1
kind: Service
metadata:
 name: redis-service
 labels:
   author: cletus
   name: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    author: cletus
    name: redis-pod